# .readthedocs.yml
# Read the Docs 配置文件
# 详情见：https://docs.readthedocs.io/en/stable/config-file/v2.html

# 必需项
version: 2

# 设置 Python 及其他工具的版本
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# 使用 Sphinx 在 docs/ 目录构建文档
sphinx:
  configuration: docs/conf.py

# 构建所有格式
formats: all

# 可选：设置构建文档所需的 Python 版本和依赖
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
