# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.


# QLib documentation build configuration file, created by
# sphinx-quickstart on Wed Sep 27 15:16:05 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

import pkg_resources


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"


# General information about the project.
project = "QLib"
copyright = "Microsoft"
author = "Microsoft"

# 您正在记录的项目的版本信息，用作|version|和|release|的替换，
# 也用于构建文档中的其他各种地方。
#
# 简短的X.Y版本。
version = pkg_resources.get_distribution("pyqlib").version
# 完整版本，包括alpha/beta/rc标签。
release = pkg_resources.get_distribution("pyqlib").version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en_US"

# 相对于源目录的模式列表，用于匹配在查找源文件时要忽略的文件和目录。
# 这些模式也会影响html_static_path和html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "hidden"]

# 要使用的Pygments（语法高亮）样式名称。
pygments_style = "sphinx"

# 如果为true，`todo`和`todoList`将生成输出，否则不生成任何内容。
todo_include_todos = False

# 如果为true，将在:func:等交叉引用文本后附加'()'。
add_function_parentheses = False

# 如果为true，当前模块名将被添加到所有描述单元标题前（如.. function::）。
add_module_names = True

# 如果为true，`todo`和`todoList`将生成输出，否则不生成任何内容。
todo_include_todos = True


# -- HTML输出选项 ----------------------------------------------------------

# 用于HTML和HTML帮助页面的主题。有关内置主题列表，请参阅文档。
#
html_theme = "sphinx_rtd_theme"

html_logo = "_static/img/logo/1.png"


# 主题选项是特定于主题的，用于进一步自定义主题的外观和感觉。
# 有关每个主题可用的选项列表，请参阅文档。
# html_context = {
#     "display_github": False,
#     "last_updated": True,
#     "commit": True,
#     "github_user": "Microsoft",
#     "github_repo": "QLib",
#     'github_version': 'master',
#     'conf_py_path': '/docs/',

# }
#
html_theme_options = {
    "logo_only": True,
    "collapse_navigation": False,
    "navigation_depth": 4,
}

# 在此处添加包含自定义静态文件（如样式表）的任何路径，相对于此目录。
# 它们在builtin静态文件之后被复制，因此名为"default.css"的文件将覆盖builtin的"default.css"。
# html_static_path = ['_static']

# 自定义侧边栏模板，必须是将文档名称映射到模板名称的字典。
#
# 这是alabaster主题所必需的
# 参考：http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "about.html",
        "navigation.html",
        "relations.html",  # 需要'show_related': True主题选项才能显示
        "searchbox.html",
    ]
}


# -- HTMLHelp输出选项 ------------------------------------------------------

# HTML帮助生成器的输出文件基名。
htmlhelp_basename = "qlibdoc"


# -- LaTeX输出选项 ---------------------------------------------------------

latex_elements = {
    # 纸张大小（'letterpaper'或'a4paper'）。
    #
    # 'papersize': 'letterpaper',
    # 字体大小（'10pt'、'11pt'或'12pt'）。
    #
    # 'pointsize': '10pt',
    # LaTeX前言的附加内容。
    #
    # 'preamble': '',
    # LaTeX图表（浮动）对齐方式
    #
    # 'figure_align': 'htbp',
}

# 将文档树分组到LaTeX文件中。元组列表
# （源起始文件，目标名称，标题，作者，文档类[howto、manual或自定义类]）。
latex_documents = [
    (master_doc, "qlib.tex", "QLib文档", "Microsoft", "manual"),
]


# -- 手册页输出选项 -------------------------------------------------------

# 每个手册页一个条目。元组列表
# （源起始文件，名称，描述，作者，手册部分）。
man_pages = [(master_doc, "qlib", "QLib文档", [author], 1)]


# -- Texinfo输出选项 -------------------------------------------------------

# 将文档树分组到Texinfo文件中。元组列表
# （源起始文件，目标名称，标题，作者，目录菜单条目，描述，类别）
texinfo_documents = [
    (
        master_doc,
        "QLib",
        "QLib文档",
        author,
        "QLib",
        "项目的一行描述。",
        "其他",
    ),
]


# -- Epub输出选项 ----------------------------------------------------------

# Dublin Core书目信息。
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# 文本的唯一标识符。可以是ISBN号或项目主页。
#
# epub_identifier = ''

# 文本的唯一标识。
#
# epub_uid = ''

# 不应打包到epub文件中的文件列表。
epub_exclude_files = ["search.html"]


autodoc_member_order = "bysource"
autodoc_default_flags = ["members"]
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
}
